### ISSUE TITLE
[Bug] MMEngine crashes trying to cast CUDA_VISIBLE_DEVICES as an integer for Multi-Instance GPUs

### ISSUE THREAD

**Issue by adrianjoshua-strutt** [open-mmlab/mmengine#1148]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmengine/issues) and [Discussions](https://github.com/open-mmlab/mmengine/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmengine).

### Environment

sys.platform = 'linux' 
Python = '3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]' 
CUDA available = True 
numpy_random_seed = 2147483648 
GPU 0 = 'NVIDIA A100 80GB PCIe MIG 1g.10gb' 
CUDA_HOME = None 
GCC = 'x86_64-linux-gnu-gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0' 
PyTorch = '2.0.1+cu117' 
TorchVision = '0.15.2+cu117' 
OpenCV = '4.7.0' 
MMEngine = '0.7.3'
Torch = '2.0.1'
CUDA = '11.7'

### Reproduces the problem - code sample

Training with MMDetection doesn't work because there is an issue with fetching the ID from CUDA_VISIBLE_DEVICES. The problem arises when MMengine tries to cast the string as an int. The issue is specifically related to using a Multi-Instance-GPU (MIG) on a remote server. Since an integer (0, 1, 2, etc.) cannot be used as the ID for CUDA_VISIBLE_DEVICES in this case, a string with a specific pattern like "CUDA_VISIBLE_DEVICES=MIG-xxx-xxx-xxx-xxxx-xxxxxx" needs to be assigned.

However, running the project without MMEngine and using vanilla PyTorch works fine.

### Reproduces the problem - command or script

"export CUDA_VISIBLE_DEVICES=MIG-xxx-xxx-xxx-xxxx-xxxxxx" 
(Where MIG-xxx-xxx-xxx-xxxx-xxxxxx is the MIG ID of the corresponding GPU)

### Reproduces the problem - error message

Traceback (most recent call last):
  File "/mmdetection/train_hyperparameter.py", line 97, in <module>
    main()
  File "/mmdetection/train_hyperparameter.py", line 93, in main
    gridSearch(cfg, hyperparameters_to_optimize)
  File "/mmdetection/train_hyperparameter.py", line 67, in gridSearch
    gridSearch(cfg, hps_left[1::], hps_left[0], hp_config)a
  File "/mmdetection/train_hyperparameter.py", line 67, in gridSearch
    gridSearch(cfg, hps_left[1::], hps_left[0], hp_config)
  File "/mmdetection/train_hyperparameter.py", line 67, in gridSearch
    gridSearch(cfg, hps_left[1::], hps_left[0], hp_config)
  File "/mmdetection/train_hyperparameter.py", line 70, in gridSearch
    trainConfig(applyConfig(cfg, hp_config))
  File "/mmdetection/train_hyperparameter.py", line 52, in trainConfig
    runner = Runner.from_cfg(cfg)
  File "/python_env/lib/python3.10/site-packages/mmengine/runner/runner.py", line 439, in from_cfg
    runner = cls(
  File "/python_env/lib/python3.10/site-packages/mmengine/runner/runner.py", line 374, in __init__
    self.log_processor = self.build_log_processor(log_processor)
  File "/python_env/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1609, in build_log_processor
    log_processor = LOG_PROCESSORS.build(log_processor_cfg)
  File "/python_env/lib/python3.10/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/python_env/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 98, in build_from_cfg
    obj_cls = registry.get(obj_type)
  File "/python_env/lib/python3.10/site-packages/mmengine/registry/registry.py", line 442, in get
    self.import_from_location()
  File "/python_env/lib/python3.10/site-packages/mmengine/registry/registry.py", line 377, in import_from_location
    print_log(
  File "/python_env/lib/python3.10/site-packages/mmengine/logging/logger.py", line 322, in print_log
    logger_instance = MMLogger.get_current_instance()
  File "/python_env/lib/python3.10/site-packages/mmengine/logging/logger.py", line 257, in get_current_instance
    cls.get_instance('mmengine')
  File "/python_env/lib/python3.10/site-packages/mmengine/utils/manager.py", line 110, in get_instance
    instance = cls(name=name, **kwargs)  # type: ignore
  File "/python_env/lib/python3.10/site-packages/mmengine/logging/logger.py", line 191, in __init__
    device_id = _get_device_id()
  File "/python_env/lib/python3.10/site-packages/mmengine/logging/logger.py", line 379, in _get_device_id
    return int(cuda_visible_devices[local_rank])
ValueError: invalid literal for int() with base 10: 'MIG-xxx-xxx-xxx-xxxx-xxxxxx'

### Additional information

The line, that is causing the issue, can be found here:

[Github](https://github.com/open-mmlab/mmengine/blob/main/mmengine/logging/logger.py#L362)

**Comment by adrianjoshua-strutt** [comment]
Just a quick update: I managed to implement a temporary fix by overriding the method and checking if CUDA_VISIBLE_DEVICES is an integer. If it's not, I simply skip the cast and return 0. This is not anoptimal solution, but my project seems to be running with out any problems.

**Comment by zhouzaida** [comment]
Hi, a simple way to fix this issue is to deprecate the `int()` conversion.

https://github.com/open-mmlab/mmengine/blob/4bc2fe1aaec2d7d1464b11d50f6165494f62ef18/mmengine/logging/logger.py#L379

```diff
- return int(cuda_visible_devices[local_rank])
+ return cuda_visible_devices[local_rank]
```

Can you try this way to check whether it works for you? If it works, are you willing to submit a commit to fix this issue?
