### ISSUE TITLE
[Bug] Transplant code error 

### ISSUE THREAD

**Issue by zbl929** [open-mmlab/mmengine#1209]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmengine/issues) and [Discussions](https://github.com/open-mmlab/mmengine/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmengine).

### Environment

I want to transplant EfficientViT to mmseg for semantic segmentation.
When registering the model, it shows that '' TypeError: module must be a class, but got <class 'function'> ''
Do you know what the reason is ? Thank you！

### Reproduces the problem - code sample

![image](https://github.com/open-mmlab/mmengine/assets/115912468/fdc9700c-b12b-4cb2-8d40-d17f573229a4)

### Reproduces the problem - command or script

I did not run through the script, but put the configuration file into the train file, I guarantee that he is OK.

### Reproduces the problem - error message

Traceback (most recent call last):
  File "D:/CV_project/mmsegmentation-0.23.0/tools/train.py", line 17, in <module>
    from mmseg.apis import init_random_seed, set_random_seed, train_segmentor
  File "D:\CV_project\mmsegmentation-0.23.0\mmseg\apis\__init__.py", line 2, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "D:\CV_project\mmsegmentation-0.23.0\mmseg\apis\inference.py", line 9, in <module>
    from mmseg.models import build_segmentor
  File "D:\CV_project\mmsegmentation-0.23.0\mmseg\models\__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "D:\CV_project\mmsegmentation-0.23.0\mmseg\models\backbones\__init__.py", line 24, in <module>
    from .efficientvit import EfficientViT
  File "D:\CV_project\mmsegmentation-0.23.0\mmseg\models\backbones\efficientvit.py", line 505, in <module>
    def EfficientViT_M0(pretrained=False, frozen_stages=0, distillation=False, fuse=False, pretrained_cfg=None, model_cfg=EfficientViT_m0):
  File "D:\Anaconda\envs\nextvit\lib\site-packages\mmcv\utils\registry.py", line 315, in _register
    self._register_module(
  File "D:\Anaconda\envs\nextvit\lib\site-packages\mmcv\utils\registry.py", line 240, in _register_module
    raise TypeError('module must be a class, '
TypeError: module must be a class, but got <class 'function'>

进程已结束,退出代码1

**Comment by zhouzaida** [comment]
Hi, what is your mmcv version? Registering function was implemented in `1.5.1 <= mmcv < 2.0.0`.

**Comment by zbl929** [comment]
Package Version
*******************************************************************
mmcls 0.25.0
mmcv-full 1.5.0
mmdet 2.23.0
mmengine 0.7.4
mmsegmentation 0.23.0
torch 1.10.0+cu111
***************************************************************


When I set mmcv _ full = 1.5.1, the error information is as follows :
![image](https://github.com/open-mmlab/mmengine/assets/115912468/0caa1bf9-253e-42d4-8627-b4b04529fc11)



When I set mmcv _ full = 1.4.0, the error information is as follows :UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
Traceback (most recent call last):
  File "D:/CV_project/mmsegmentation-0.23.0/tools/train.py", line 17, in <module>
    from mmseg.apis import init_random_seed, set_random_seed, train_segmentor
  File "D:\CV_project\mmsegmentation-0.23.0\mmseg\apis\__init__.py", line 2, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "D:\CV_project\mmsegmentation-0.23.0\mmseg\apis\inference.py", line 9, in <module>
    from mmseg.models import build_segmentor
  File "D:\CV_project\mmsegmentation-0.23.0\mmseg\models\__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "D:\CV_project\mmsegmentation-0.23.0\mmseg\models\backbones\__init__.py", line 7, in <module>
    from .fast_scnn import FastSCNN
  File "D:\CV_project\mmsegmentation-0.23.0\mmseg\models\backbones\fast_scnn.py", line 7, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "D:\CV_project\mmsegmentation-0.23.0\mmseg\models\decode_heads\__init__.py", line 2, in <module>
    from .ann_head import ANNHead
  File "D:\CV_project\mmsegmentation-0.23.0\mmseg\models\decode_heads\ann_head.py", line 8, in <module>
    from .decode_head import BaseDecodeHead
  File "D:\CV_project\mmsegmentation-0.23.0\mmseg\models\decode_heads\decode_head.py", line 11, in <module>
    from ..losses import accuracy
  File "D:\CV_project\mmsegmentation-0.23.0\mmseg\models\losses\__init__.py", line 6, in <module>
    from .focal_loss import FocalLoss
  File "D:\CV_project\mmsegmentation-0.23.0\mmseg\models\losses\focal_loss.py", line 6, in <module>
    from mmcv.ops import sigmoid_focal_loss as _sigmoid_focal_loss
  File "D:\Anaconda\envs\nextvit\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "D:\Anaconda\envs\nextvit\lib\site-packages\mmcv\ops\assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File "D:\Anaconda\envs\nextvit\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "D:\Anaconda\envs\nextvit\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: 找不到指定的模块。

进程已结束,退出代码1

**Comment by zbl929** [comment]
As a matter of fact, when mmsegmentation 0.23.0 and mmcv-full==1.5.0, I registered a module successfully and achieved good results. The registration model at that time was like this.
![image](https://github.com/open-mmlab/mmengine/assets/115912468/a55a7f81-3ee1-4103-b2b4-b185a7705223)

**Comment by zbl929** [comment]
When I used to register a module, I met three situations 

1.Nextvit is the module that I registered successfully .
![image](https://github.com/open-mmlab/mmengine/assets/115912468/bf8fcdc4-c3be-4a64-bf1e-40447e2a4a65)
I also tried to register the other two modules, but failed. Here 's what he looks like.

2.He first registered Vanillanet, but re-registered the vanillanet _ 5 module in another file. I can only use Vanillanet, but I don 't know how to use vanillanet _ 5.
![image](https://github.com/open-mmlab/mmengine/assets/115912468/0a892f29-9531-473a-a900-af04ea2398bd)
![image](https://github.com/open-mmlab/mmengine/assets/115912468/0d4e9562-0d84-45d9-af98-7d4b4e7a0076)

3.The third is the module that I discussed with you before. It is not a class, but a function, and then the error message is as follows：
TypeError: module must be a class, but got <class 'function'>
![image](https://github.com/open-mmlab/mmengine/assets/115912468/9a0c398c-fe72-4a20-82b2-30e612f68fea)

**Comment by zbl929** [comment]
Thank you very much, hope to answer

**Comment by zhouzaida** [comment]
Duplicated with https://github.com/open-mmlab/mmcv/issues/2846. I will reply the issue in mmcv.
