### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by KyanChen** [open-mmlab/mmengine#1408]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmengine/issues) and [Discussions](https://github.com/open-mmlab/mmengine/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmengine).

### Environment

load deepspeed ckpt for test

### Reproduces the problem - code sample

Traceback (most recent call last):
  File "/mnt/nlp-ali/usr/chenkeyan/codes/mm_market/tools/test.py", line 197, in <module>
    main()
  File "/mnt/nlp-ali/usr/chenkeyan/codes/mm_market/tools/test.py", line 190, in main
    metrics = runner.test()
  File "/root/miniconda3/envs/torch2mmcv2/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1250, in test
    self.load_or_resume()
  File "/root/miniconda3/envs/torch2mmcv2/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1141, in load_or_resume
    self.resume(resume_from)
  File "/root/miniconda3/envs/torch2mmcv2/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1455, in resume
    checkpoint = self.strategy.resume(
  File "/root/miniconda3/envs/torch2mmcv2/lib/python3.10/site-packages/mmengine/_strategy/deepspeed.py", line 451, in resume
    self.load_optim_state_dict(extra_ckpt.pop('optim_wrapper'))
  File "/root/miniconda3/envs/torch2mmcv2/lib/python3.10/site-packages/mmengine/_strategy/base.py", line 805, in load_optim_state_dict
    self.optim_wrapper.load_state_dict(state_dict)
AttributeError: 'DeepSpeedStrategy' object has no attribute 'optim_wrapper'

### Reproduces the problem - command or script

load deepspeed ckpt for test

### Reproduces the problem - error message

Traceback (most recent call last):
  File "/mnt/nlp-ali/usr/chenkeyan/codes/mm_market/tools/test.py", line 197, in <module>
    main()
  File "/mnt/nlp-ali/usr/chenkeyan/codes/mm_market/tools/test.py", line 190, in main
    metrics = runner.test()
  File "/root/miniconda3/envs/torch2mmcv2/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1250, in test
    self.load_or_resume()
  File "/root/miniconda3/envs/torch2mmcv2/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1141, in load_or_resume
    self.resume(resume_from)
  File "/root/miniconda3/envs/torch2mmcv2/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1455, in resume
    checkpoint = self.strategy.resume(
  File "/root/miniconda3/envs/torch2mmcv2/lib/python3.10/site-packages/mmengine/_strategy/deepspeed.py", line 451, in resume
    self.load_optim_state_dict(extra_ckpt.pop('optim_wrapper'))
  File "/root/miniconda3/envs/torch2mmcv2/lib/python3.10/site-packages/mmengine/_strategy/base.py", line 805, in load_optim_state_dict
    self.optim_wrapper.load_state_dict(state_dict)
AttributeError: 'DeepSpeedStrategy' object has no attribute 'optim_wrapper'

**Comment by KyanChen** [comment]
There need a optimer_warp for deepspeed strategy for testing.
https://github.com/open-mmlab/mmengine/blob/e43bbb5e03a412ea07f9ef6d0f118586082c2845/mmengine/runner/_flexible_runner.py#L1247C1-L1247C75

**Comment by SCZwangxiao** [comment]
> There need a optimer_warp for deepspeed strategy for testing. https://github.com/open-mmlab/mmengine/blob/e43bbb5e03a412ea07f9ef6d0f118586082c2845/mmengine/runner/_flexible_runner.py#L1247C1-L1247C75

Seems that it has not been fixed yet.
