### ISSUE TITLE
 'hybrid_parallel' plugin in 'ColossalAIStrategy'  is not supported in mmengin-0.10.0

### ISSUE THREAD

**Issue by taohan10200** [open-mmlab/mmengine#1432]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmengine/issues) and [Discussions](https://github.com/open-mmlab/mmengine/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmengine).

### Environment

-

### Reproduces the problem - code sample

```
strategy = dict(
    type='ColossalAIStrategy',
    plugin = 'hybrid_parallel',
    config=dict(pipeline=2,
                tensor=dict(mode='1d', 
                            size=2)
                ),
    mixed_precision='fp16',
    )
```

### Reproduces the problem - command or script

-

### Reproduces the problem - error message

```
[11/21/23 19:23:32] INFO     colossalai - colossalai - INFO:                    
                             /mnt/petrelfs/hantao.dispatch/anaconda3/envs/nwp/li
                             b/python3.10/site-packages/colossalai/initialize.py
                             :63 launch                                         
                    INFO     colossalai - colossalai - INFO: Distributed        
                             environment is initialized, world size: 4          
Traceback (most recent call last):
  File "/mnt/petrelfs/hantao.dispatch/NWP/EarthVision_v1/tools/train.py", line 140, in <module>
Traceback (most recent call last):
  File "/mnt/petrelfs/hantao.dispatch/NWP/EarthVision_v1/tools/train.py", line 140, in <module>
Traceback (most recent call last):
  File "/mnt/petrelfs/hantao.dispatch/NWP/EarthVision_v1/tools/train.py", line 140, in <module>
Traceback (most recent call last):
  File "/mnt/petrelfs/hantao.dispatch/NWP/EarthVision_v1/tools/train.py", line 140, in <module>
    main()
    main()
  File "/mnt/petrelfs/hantao.dispatch/NWP/EarthVision_v1/tools/train.py", line 134, in main
  File "/mnt/petrelfs/hantao.dispatch/NWP/EarthVision_v1/tools/train.py", line 134, in main
    main()
  File "/mnt/petrelfs/hantao.dispatch/NWP/EarthVision_v1/tools/train.py", line 134, in main
    main()
  File "/mnt/petrelfs/hantao.dispatch/NWP/EarthVision_v1/tools/train.py", line 134, in main
    runner = RUNNERS.build(cfg)
  File "/mnt/petrelfs/hantao.dispatch/NWP/mmengine_0.9/mmengine/mmengine/registry/registry.py", line 570, in build
    runner = RUNNERS.build(cfg)
  File "/mnt/petrelfs/hantao.dispatch/NWP/mmengine_0.9/mmengine/mmengine/registry/registry.py", line 570, in build
    runner = RUNNERS.build(cfg)
  File "/mnt/petrelfs/hantao.dispatch/NWP/mmengine_0.9/mmengine/mmengine/registry/registry.py", line 570, in build
    runner = RUNNERS.build(cfg)
  File "/mnt/petrelfs/hantao.dispatch/NWP/mmengine_0.9/mmengine/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/mnt/petrelfs/hantao.dispatch/NWP/mmengine_0.9/mmengine/mmengine/registry/build_functions.py", line 196, in build_runner_from_cfg
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/mnt/petrelfs/hantao.dispatch/NWP/mmengine_0.9/mmengine/mmengine/registry/build_functions.py", line 196, in build_runner_from_cfg
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/mnt/petrelfs/hantao.dispatch/NWP/mmengine_0.9/mmengine/mmengine/registry/build_functions.py", line 196, in build_runner_from_cfg
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/mnt/petrelfs/hantao.dispatch/NWP/mmengine_0.9/mmengine/mmengine/registry/build_functions.py", line 196, in build_runner_from_cfg
    runner = runner_cls.from_cfg(args)  # type: ignore
  File "/mnt/petrelfs/hantao.dispatch/NWP/EarthVision_v1/nwp/engine/runner/_flexible_runner.py", line 422, in from_cfg
    runner = runner_cls.from_cfg(args)  # type: ignore
  File "/mnt/petrelfs/hantao.dispatch/NWP/EarthVision_v1/nwp/engine/runner/_flexible_runner.py", line 422, in from_cfg
    runner = runner_cls.from_cfg(args)  # type: ignore
  File "/mnt/petrelfs/hantao.dispatch/NWP/EarthVision_v1/nwp/engine/runner/_flexible_runner.py", line 422, in from_cfg
    runner = runner_cls.from_cfg(args)  # type: ignore
  File "/mnt/petrelfs/hantao.dispatch/NWP/EarthVision_v1/nwp/engine/runner/_flexible_runner.py", line 422, in from_cfg
    runner = cls(
    runner = cls(
  File "/mnt/petrelfs/hantao.dispatch/NWP/EarthVision_v1/nwp/engine/runner/_flexible_runner.py", line 362, in __init__
  File "/mnt/petrelfs/hantao.dispatch/NWP/EarthVision_v1/nwp/engine/runner/_flexible_runner.py", line 362, in __init__
    runner = cls(
  File "/mnt/petrelfs/hantao.dispatch/NWP/EarthVision_v1/nwp/engine/runner/_flexible_runner.py", line 362, in __init__
    runner = cls(
  File "/mnt/petrelfs/hantao.dispatch/NWP/EarthVision_v1/nwp/engine/runner/_flexible_runner.py", line 362, in __init__
    self.strategy = self.build_strategy(
  File "/mnt/petrelfs/hantao.dispatch/NWP/EarthVision_v1/nwp/engine/runner/_flexible_runner.py", line 664, in build_strategy
    self.strategy = self.build_strategy(
  File "/mnt/petrelfs/hantao.dispatch/NWP/EarthVision_v1/nwp/engine/runner/_flexible_runner.py", line 664, in build_strategy
    self.strategy = self.build_strategy(
  File "/mnt/petrelfs/hantao.dispatch/NWP/EarthVision_v1/nwp/engine/runner/_flexible_runner.py", line 664, in build_strategy
    self.strategy = self.build_strategy(
  File "/mnt/petrelfs/hantao.dispatch/NWP/EarthVision_v1/nwp/engine/runner/_flexible_runner.py", line 664, in build_strategy
    strategy_obj = STRATEGIES.build(strategy)
  File "/mnt/petrelfs/hantao.dispatch/NWP/mmengine_0.9/mmengine/mmengine/registry/registry.py", line 570, in build
    strategy_obj = STRATEGIES.build(strategy)
  File "/mnt/petrelfs/hantao.dispatch/NWP/mmengine_0.9/mmengine/mmengine/registry/registry.py", line 570, in build
    strategy_obj = STRATEGIES.build(strategy)
  File "/mnt/petrelfs/hantao.dispatch/NWP/mmengine_0.9/mmengine/mmengine/registry/registry.py", line 570, in build
    strategy_obj = STRATEGIES.build(strategy)
  File "/mnt/petrelfs/hantao.dispatch/NWP/mmengine_0.9/mmengine/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/mnt/petrelfs/hantao.dispatch/NWP/mmengine_0.9/mmengine/mmengine/registry/build_functions.py", line 121, in build_from_cfg
  File "/mnt/petrelfs/hantao.dispatch/NWP/mmengine_0.9/mmengine/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/mnt/petrelfs/hantao.dispatch/NWP/mmengine_0.9/mmengine/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/mnt/petrelfs/hantao.dispatch/NWP/mmengine_0.9/mmengine/mmengine/_strategy/colossalai.py", line 266, in __init__
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/mnt/petrelfs/hantao.dispatch/NWP/mmengine_0.9/mmengine/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/mnt/petrelfs/hantao.dispatch/NWP/mmengine_0.9/mmengine/mmengine/_strategy/colossalai.py", line 266, in __init__
    plugin = self._build_plugin(plugin)
  File "/mnt/petrelfs/hantao.dispatch/NWP/mmengine_0.9/mmengine/mmengine/_strategy/colossalai.py", line 476, in _build_plugin
    obj = obj_cls(**args)  # type: ignore
  File "/mnt/petrelfs/hantao.dispatch/NWP/mmengine_0.9/mmengine/mmengine/_strategy/colossalai.py", line 266, in __init__
    plugin = self._build_plugin(plugin)
  File "/mnt/petrelfs/hantao.dispatch/NWP/mmengine_0.9/mmengine/mmengine/_strategy/colossalai.py", line 476, in _build_plugin
    obj = obj_cls(**args)  # type: ignore
  File "/mnt/petrelfs/hantao.dispatch/NWP/mmengine_0.9/mmengine/mmengine/_strategy/colossalai.py", line 266, in __init__
    raise ValueError('`plugin` must be "gemini" or '
    raise ValueError('`plugin` must be "gemini" or '
    plugin = self._build_plugin(plugin)
  File "/mnt/petrelfs/hantao.dispatch/NWP/mmengine_0.9/mmengine/mmengine/_strategy/colossalai.py", line 476, in _build_plugin
ValueError: `plugin` must be "gemini" or "lowlevel-zero"
ValueError: `plugin` must be "gemini" or "lowlevel-zero"
    plugin = self._build_plugin(plugin)
  File "/mnt/petrelfs/hantao.dispatch/NWP/mmengine_0.9/mmengine/mmengine/_strategy/colossalai.py", line 476, in _build_plugin
    raise ValueError('`plugin` must be "gemini" or '
ValueError: `plugin` must be "gemini" or "lowlevel-zero"
    raise ValueError('`plugin` must be "gemini" or '
ValueError: `plugin` must be "gemini" or "lowlevel-zero"
```

### Additional information

Does "hybrid_parallel" plugin is not supported in mmengine-0.10.0?

**Comment by fanqiNO1** [comment]
Yes, for `ColossalAIStrategy`, we currently only support plugins `gemini` and `lowlevel-zero`, you can refer to https://github.com/open-mmlab/mmengine/blob/main/mmengine/_strategy/colossalai.py#L476
