### ISSUE TITLE
[Bug] fail to build with python 3.13

### ISSUE THREAD

**Issue by hubutui** [open-mmlab/mmengine#1616]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmengine/issues) and [Discussions](https://github.com/open-mmlab/mmengine/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmengine).

### Environment

none

### Reproduces the problem - code sample

none

### Reproduces the problem - command or script

```bash
python -m build --wheel --no-isolation
```

### Reproduces the problem - error message

```
==> Starting build()...
* Getting build dependencies for wheel...
<string>:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
    main()
    ~~~~^^
  File "/usr/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in main
    json_out["return_val"] = hook(**hook_input["kwargs"])
                             ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/usr/lib/python3.13/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
    self.run_setup()
    ~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/setuptools/build_meta.py", line 516, in run_setup
    super().run_setup(setup_script=setup_script)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/setuptools/build_meta.py", line 318, in run_setup
    exec(code, locals())
    ~~~~^^^^^^^^^^^^^^^^
  File "<string>", line 131, in <module>
  File "<string>", line 32, in get_version
KeyError: '__version__'

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
```

### Additional information

quick fix, update `get_version` in `setup.py`:
```python
def get_version():
    version_dict = {}
    with open(version_file) as f:
        exec(compile(f.read(), version_file, 'exec'), version_dict)
    return version_dict['__version__']
```

see also https://docs.python.org/3/whatsnew/3.13.html#defined-mutation-semantics-for-locals

**Comment by hubutui** [comment]
This also apply to mmcv https://github.com/open-mmlab/mmcv/blob/761d780a24c118f383868d4d78fd3fe429ae95d5/setup.py#L39-L43

**Comment by hubutui** [comment]
and mmdetection https://github.com/open-mmlab/mmdetection/blob/cfd5d3a985b0249de009b67d04f37263e11cdf3d/setup.py#L25-L28

**Comment by hubutui** [comment]
and mmaction2 https://github.com/open-mmlab/mmaction2/blob/4d6c93474730cad2f25e51109adcf96824efc7a3/setup.py#L19-L22

**Comment by hubutui** [comment]
and mmsegmentation https://github.com/open-mmlab/mmsegmentation/blob/b040e147adfa027bbc071b624bedf0ae84dfc922/setup.py#L20-L23

**Comment by hubutui** [comment]
and mmpose https://github.com/open-mmlab/mmpose/blob/71ec36ebd63c475ab589afc817868e749a61491f/setup.py#L25-L34

**Comment by sarahec** [comment]
These are due to setuptools 83 dropping `pkg_resources`. Use Python's built-in `importlib` on python >= 3.9
