### ISSUE TITLE
Can't replace fields with environment variables[Bug] 

### ISSUE THREAD

**Issue by VJoer** [open-mmlab/mmengine#940]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmengine/issues) and [Discussions](https://github.com/open-mmlab/mmengine/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmengine).

### Environment

```shell
pip list | grep mm
mmcv               2.0.0rc4
mmdeploy           1.0.0rc1     /workspace/mmdeploy
mmdet              3.0.0rc5     /workspace/mmdetection
mmengine           0.5.0
mmyolo             0.4.0        /workspace/mmyolo
```

### Reproduces the problem - code sample

demo_train.py 
```python
import argparse

from mmengine.config import Config, DictAction


def parse_args():
    parser = argparse.ArgumentParser(description='Train a model')
    parser.add_argument('config', help='train config file path')
    parser.add_argument(
        '--cfg-options',
        nargs='+',
        action=DictAction,
        help='override some settings in the used config, the key-value pair '
        'in xxx=yyy format will be merged into config file. If the value to '
        'be overwritten is a list, it should be like key="[a,b]" or key=a,b '
        'It also allows nested list/tuple values, e.g. key="[(a,b),(c,d)]" '
        'Note that the quotation marks are necessary and that no white space '
        'is allowed.')

    args = parser.parse_args()
    return args


def main():
    args = parse_args()
    cfg = Config.fromfile(args.config)
    if args.cfg_options is not None:
        cfg.merge_from_dict(args.cfg_options)
    print(cfg)


if __name__ == '__main__':
    main()
```
replace_data_root.py
```python
dataset_type = 'CocoDataset'
data_root = '{{$DATASET:/data/coco/}}'
dataset = dict(ann_file=data_root + 'train.json')
```
replace_num_classes.py
```python
model = dict(bbox_head=dict(num_classes={{'$NUM_CLASSES:80'}}))
```

### Reproduces the problem - command or script

```shell
python demo_train.py replace_data_root.py 
Config (path: replace_data_root.py): {'dataset_type': 'CocoDataset', 'data_root': '{{$DATASET:/data/coco/}}', 'dataset': {'ann_file': '{{$DATASET:/data/coco/}}train.json'}}
```

```shell
DATASET=/new/dataset/path/ python demo_train.py replace_data_root.py
Config (path: replace_data_root.py): {'dataset_type': 'CocoDataset', 'data_root': '{{$DATASET:/data/coco/}}', 'dataset': {'ann_file': '{{$DATASET:/data/coco/}}train.json'}}
```

### Reproduces the problem - error message
```shell
NUM_CLASSES=20 python demo_train.py replace_num_classes.py
Traceback (most recent call last):
  File "demo_train.py", line 33, in <module>
    main()
  File "demo_train.py", line 26, in main
    cfg = Config.fromfile(args.config)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/config/config.py", line 172, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "/usr/local/lib/python3.8/dist-packages/mmengine/config/config.py", line 432, in _file2dict
    eval(codeobj, global_locals_var, global_locals_var)
  File "", line 1, in <module>
TypeError: unhashable type: 'set'
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f980cd169d0>
Traceback (most recent call last):
  File "/usr/lib/python3.8/tempfile.py", line 579, in __del__
    self.close()
  File "/usr/lib/python3.8/tempfile.py", line 575, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmplcyfu_uo/tmpse7rg7br.py'
```

### Additional information
Environment variables are not being replaced correctly

**Comment by HAOCHENYE** [comment]
Hi, you should configure `num_classes={{'$NUM_CLASSES:80'}}` as `num_classes='{{$NUM_CLASSES:80}}'`

**Comment by VJoer** [comment]
cmd
```shell
NUM_CLASSES=20 python demo_train.py replace_num_classes.py
```
output
```shell
Config (path: replace_num_classes.py): {'model': {'bbox_head': {'num_classes': '{{$NUM_CLASSES:80}}'}}}
```
What I mean is that the environment variable does not replace the Settings in the config file, NUM_CLASSES=20 is not being replaced correctly

**Comment by HAOCHENYE** [comment]
This feature is integrated after MMEngine v0.5.0, therefore you need to use the MMEngine of the latest main.

I noticed that the way environment variables are referenced in the examples is inconsistent. Therefore, I suggest that they should be modified to be the same for solving the problem :rofl: . However, the fact has proven that both writing styles are correct :rofl: .

**Comment by VJoer** [comment]
I'm using the latest mmengine, but it not work for me
```shell
root@gz-cs-gpu-3-107:/workspace/temp# pip list | grep mmengine
mmengine           0.5.0
```
