### ISSUE TITLE
[Bug] from mmdet.apis import init_detector, inference_detector

### ISSUE THREAD

**Issue by Vaibhav-Fulara** [open-mmlab/mmengine#967]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmengine/issues) and [Discussions](https://github.com/open-mmlab/mmengine/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmengine).

### Environment

Using NVIDIA Jetson Xavier3 using pip3 and command:
python3 -m pip install --upgrade pip; python3 -m pip install aiohttp numpy=='1.19.4' scipy=='1.5.3' export "LD_LIBRARY_PATH=/usr/lib/llvm-8/lib:$LD_LIBRARY_PATH"; python3 -m pip install --upgrade protobuf; python3 -m pip install --no-cache $TORCH_INSTALL

### Reproduces the problem - code sample

```
from mmdet.apis import init_detector, inference_detector
```

### Reproduces the problem - command or script

```
from mmdet.apis import init_detector, inference_detector
```

### Reproduces the problem - error message

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xavier3/mmdetection/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/xavier3/mmdetection/mmdet/apis/inference.py", line 10, in <module>
    from mmcv.ops import RoIPool
  File "/home/xavier3/.local/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/home/xavier3/.local/lib/python3.8/site-packages/mmcv/ops/active_rotated_filter.py", line 8, in <module>
    from ..utils import ext_loader
  File "/home/xavier3/.local/lib/python3.8/site-packages/mmcv/utils/__init__.py", line 4, in <module>
    from .env import collect_env
  File "/home/xavier3/.local/lib/python3.8/site-packages/mmcv/utils/env.py", line 8, in <module>
    from mmengine.utils.dl_utils import collect_env as mmengine_collect_env
  File "/home/xavier3/.local/lib/python3.8/site-packages/mmengine/utils/dl_utils/__init__.py", line 8, in <module>
    from .time_counter import TimeCounter
  File "/home/xavier3/.local/lib/python3.8/site-packages/mmengine/utils/dl_utils/time_counter.py", line 7, in <module>
    from mmengine.dist.utils import master_only
  File "/home/xavier3/.local/lib/python3.8/site-packages/mmengine/dist/__init__.py", line 2, in <module>
    from .dist import (all_gather_object, all_reduce, all_gather, all_reduce_dict,
  File "/home/xavier3/.local/lib/python3.8/site-packages/mmengine/dist/dist.py", line 15, in <module>
    from torch.distributed import ProcessGroup
ImportError: cannot import name 'ProcessGroup' from 'torch.distributed' (/home/xavier3/.local/lib/python3.8/site-packages/torch/distributed/__init__.py)

```

### Additional information

1. Pytorch version: 1.12.0a0+02fb0b0f.nv22.06
2. MMEngine version: 0.6.0
3. MMDetection version: 3.0.0rc5
4. mmcv version:  2.0.0rc4
5. Python version: 3.8.10

**Comment by zhouzaida** [comment]
Hi @Vaibhav-Fulara , the error shown above is `ImportError: cannot import name 'ProcessGroup' from 'torch.distributed'` so you could check whether the torch was installed successfully.

**Comment by Vaibhav-Fulara** [comment]
Hi @zhouzaida, Thanks for your time! I installed the currrent torch version using the commands provided in the nvidia official documentation: https://docs.nvidia.com/deeplearning/frameworks/install-pytorch-jetson-platform/index.html (generic install without version / JetPack specification) and the install was successful but I'm still getting this error

**Comment by zhouzaida** [comment]
Hi, what is the output of `torch.distributed.is_available()`? If it is False, probably torch was not installed successfully and you can open an issue in PyTorch or NVIDIA.
